@startuml

activate "自分: プレイヤー"
"自分: プレイヤー" -> "自分の手札: 手札" : カードを加える(カード)
activate "自分の手札: 手札"
deactivate "自分の手札: 手札"

"自分: プレイヤー" -> "自分の手札: 手札" : 同じ数のカードを探す()
activate "自分の手札: 手札"
"自分: プレイヤー" <-- "自分の手札: 手札" : カード
deactivate "自分の手札: 手札"

"自分: プレイヤー" -> "テーブル" : [同じ数のカードが存在した場合] カードを捨てる(カード)
activate テーブル
deactivate テーブル

"自分: プレイヤー" -> "自分の手札: 手札" : 枚数を数える()
activate "自分の手札: 手札"
"自分: プレイヤー" <-- "自分の手札: 手札" : 枚数
deactivate "自分の手札: 手札"

"自分: プレイヤー" -> 進行役 : [手札がなくなった場合] 上がりを宣言する()
activate 進行役
deactivate 進行役
deactivate "自分: プレイヤー"

@enduml
