@startuml

activate 進行役
進行役 -> "自分: プレイヤー" : 順番を指名する(隣のプレイヤー)

activate "自分: プレイヤー"
"自分: プレイヤー" -> "隣のプレイヤー: プレイヤー" : 手札を出す()

activate "隣のプレイヤー: プレイヤー"
"自分: プレイヤー" <-- "隣のプレイヤー: プレイヤー" : 手札
deactivate "隣のプレイヤー: プレイヤー"

"自分: プレイヤー" -> "隣のプレイヤーの手札: 手札" : カードを引く()
activate "隣のプレイヤーの手札: 手札"
"自分: プレイヤー" <-- "隣のプレイヤーの手札: 手札" : カード
deactivate "隣のプレイヤーの手札: 手札"

deactivate "自分: プレイヤー"

@enduml
