@startuml

class プレーヤー {
  パスした回数
  カードを配る()
  順番を指名する()
}

class 進行役 {
  上がりを宣言する()
  パス回数の超過を宣言する()
}

class カード {
  数
  スート
}

class 手札 {
  カードの枚数
  シャッフルする()
  7を探す()
  配置できるカードを探す()
  枚数を数える()
}

class テーブル {
  並べたカード
  カードを置く()
  パスをする()
}

プレーヤー -l- 進行役 : ゲームを進める
プレーヤー -- プレーヤー : 対戦相手
プレーヤー -u- テーブル : カードを置く
プレーヤー -- 手札 : 持っている
進行役 -- 手札 : 持っている
手札 -- カード : 構成する

@enduml
