@startuml

class プレーヤー {
  名前
  パス回数
  カードを配る()
  順番を指名する()
  パス回数を数える()
}

class 進行役 {
  ゲームを準備する()
  ゲームを開始する()
  パスを宣言する()
  上がりを宣言する()
}

class カード {
  数
  スート
  数字を見る()
  スートを見る()
}

class 手札 {
  カードの枚数
  カードを加える()
  カードを引く()
  カードを見る()
  枚数を数える()
  シャッフルする()
}

class テーブル {
  カードを置く()
  カードを見る()
}

プレーヤー -l- 進行役 : ゲームを進める
プレーヤー -- プレーヤー : 対戦相手
プレーヤー -u- テーブル : カードを置く
プレーヤー -- 手札 : 持っている
進行役 -- 手札 : 持っている
手札 -- カード : 構成する

@enduml
