@startuml

class プレイヤー {
  カードを配る() : 必要に応じてサブクラスで拡張
  順番を指名する() : 実際の処理はサブクラスで記述
}

class 進行役 {
  ゲームを準備する()
  ゲームを開始する()
  上がりを宣言する()
}

class カード {
  数を見る()
  スートを見る()
}

class 手札 {
  カードを加える()
  カードを引く()
  カードを見る() : あとで検討
  枚数を数える()
  シャッフルする()
}

class テーブル {
  カードを置く() : 実際の処理はサブクラスで記述
  カードを見る() : 実際の処理はサブクラスで記述
}

@enduml
