@startuml

activate ":プレイヤー"
":プレイヤー" -> ":ルール" : テーブルに置けるカードを探す()

activate ":ルール"
":ルール" -> ":手札" : カードを見る()
activate ":手札"
deactivate ":手札"

":ルール" -> ":テーブル" : カードを見る()
activate ":テーブル"
deactivate ":テーブル"

":ルール" -> ":ルール" : テーブルに置けるカードを判断する()
activate ":ルール"
deactivate ":ルール"

":プレイヤー" <-- ":ルール" : カード
deactivate ":ルール"


@enduml
