@startuml

activate ":進行役"
":進行役" -> "進行役の手札 :手札" : シャッフルする()

loop 進行役の手札がなくなるまで
  activate "進行役の手札 :手札"
  deactivate "進行役の手札 :手札"

  ":進行役" -> "進行役の手札 :手札" : カードを引く()
  activate "進行役の手札 :手札"
  ":進行役" <-- "進行役の手札 :手札" : カード
  deactivate "進行役の手札 :手札"

  ":進行役" -> ":プレイヤー" : カードを受け取る()
  activate ":プレイヤー"

  ":プレイヤー" -> ":カード" : 数を知る()
  activate ":カード"
  ":プレイヤー" <-- ":カード" : 数
  deactivate ":カード"

  ":プレイヤー" -> ":テーブル" : [数が7である場合]カードを置く()
  activate ":テーブル"
  deactivate ":テーブル"

  ":プレイヤー" -> "プレイヤーの手札 :手札" : [数が7以外の場合]カードを加える()
  activate "プレイヤーの手札 :手札"
  deactivate "プレイヤーの手札 :手札"

  deactivate ":プレイヤー"
end

deactivate ":進行役"

@enduml
