@startuml

activate ":進行役"
  ":進行役" -> ":プレイヤー" : 順番を指名する()

loop 手札のすべてのカードについて行う
  activate ":プレイヤー"

  ":プレイヤー" -> ":手札" : カードを見る()
  activate ":手札"
  ":プレイヤー" <-- ":手札" : カード
  deactivate ":手札"

  ":プレイヤー" -> ":テーブル" : カードを見る(位置)
  activate ":テーブル"
  deactivate ":テーブル"

  ":プレイヤー" -> ":手札" : [カードを置ける場合]カードを引く()
  activate ":手札"
  ":プレイヤー" <-- ":手札" : カード
  deactivate ":手札"

  ":プレイヤー" -> ":テーブル" : [カードが置ける場合]カードを置く()
  activate ":テーブル"
  deactivate ":テーブル"

  ":プレイヤー" -> ":進行役" : [カードが置けない場合]パスを宣言する()
  activate ":進行役"
  deactivate ":進行役"

  ":プレイヤー" -> ":手札" : 枚数を知る()
  activate ":手札"
  ":プレイヤー" <-- ":手札" : 枚数
  deactivate ":手札"

  ":プレイヤー" -> ":進行役" : [手札がなくなった場合]上がりを宣言する
  activate ":進行役"
  deactivate ":進行役"

  deactivate ":プレイヤー"
end

deactivate ":進行役"

@enduml
