@startuml

activate 進行役
進行役 -> "進行役の手札: 手札" : シャッフルする()

loop 進行役の手札がなくなるまで
  activate "進行役の手札: 手札"
  進行役 -> "進行役の手札: 手札" : カードを引く()
  進行役 <-- "進行役の手札: 手札" : カード
  deactivate "進行役の手札: 手札"

  activate プレイヤー
  進行役 -> プレイヤー : カードを配る(カード)

  activate "プレイヤーの手札: 手札"
  プレイヤー -> "プレイヤーの手札: 手札" : カードを加える(カード)

  プレイヤー -> "プレイヤーの手札: 手札" : 同じ数のカードを探す()
  プレイヤー <-- "プレイヤーの手札: 手札" : カード
  deactivate "プレイヤーの手札: 手札"

  activate テーブル
  プレイヤー -> テーブル : [同じ数のカードが存在した場合] カードを捨てる(カード)
  deactivate テーブル
end

@enduml
